"""Validated ontology loading and fuzzy matching."""

from neural_search.ontology.loader import (
    DEFAULT_ONTOLOGY_PATH,
    DEFAULT_BRAIN_REGIONS_PATH,
    OntologyValidationError,
    get_brain_regions,
    get_all_tasks,
    get_ontology,
    get_task_by_id,
    load_brain_regions,
    load_ontology,
    reload_ontology,
    validate_ontology,
)
from neural_search.ontology.matcher import (
    OntologyMatcher,
    expand_query_terms,
    expand_query_terms_with_graph,
    match_affordances,
    match_all,
    match_behavior_labels,
    match_brain_regions,
    match_modalities,
    match_tasks,
    normalize_text,
)
from neural_search.ontology.models import (
    AnalysisAffordance,
    BehaviorLabel,
    BrainRegion,
    LabelMatch,
    Ontology,
    Task,
)

__all__ = [
    "AnalysisAffordance",
    "BehaviorLabel",
    "BrainRegion",
    "DEFAULT_BRAIN_REGIONS_PATH",
    "DEFAULT_ONTOLOGY_PATH",
    "LabelMatch",
    "Ontology",
    "OntologyMatcher",
    "OntologyValidationError",
    "Task",
    "expand_query_terms",
    "expand_query_terms_with_graph",
    "get_all_tasks",
    "get_ontology",
    "get_task_by_id",
    "load_ontology",
    "match_affordances",
    "match_all",
    "match_behavior_labels",
    "match_brain_regions",
    "match_modalities",
    "match_tasks",
    "normalize_text",
    "get_brain_regions",
    "load_brain_regions",
    "reload_ontology",
    "validate_ontology",
]
