"""Render dataset cards as Markdown."""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import sys
    sys.path.insert(0, str(__file__).rsplit("/packages", 1)[0] + "/packages")
    from shared.schemas import DatasetCard


class MarkdownRenderer:
    """Render DatasetCard to Markdown format."""

    def render(self, card: "DatasetCard") -> str:
        """
        Render a dataset card as Markdown.

        Args:
            card: The dataset card to render.

        Returns:
            Markdown string.
        """
        lines = []

        # Title
        lines.append(f"# {card.title}")
        lines.append("")

        # Summary
        lines.append(f"> {card.summary}")
        lines.append("")

        # Metadata badges
        badges = []
        badges.append(f"**Source:** {card.source.value.upper()}")
        if card.data_standard:
            badges.append(f"**Format:** {card.data_standard.value.upper()}")
        if card.readiness:
            score_pct = int(card.readiness.score * 100)
            badges.append(f"**Readiness:** {score_pct}%")
        lines.append(" | ".join(badges))
        lines.append("")

        # Core metadata
        lines.append("## Overview")
        lines.append("")

        if card.species:
            lines.append(f"- **Species:** {', '.join(card.species)}")
        if card.tasks:
            lines.append(f"- **Tasks:** {', '.join(card.tasks)}")
        if card.modalities:
            lines.append(f"- **Modalities:** {', '.join(card.modalities)}")
        if card.brain_regions:
            lines.append(f"- **Brain Regions:** {', '.join(card.brain_regions)}")
        lines.append("")

        # Links
        if card.url or card.doi:
            lines.append("## Links")
            lines.append("")
            if card.url:
                lines.append(f"- [Dataset URL]({card.url})")
            if card.doi:
                lines.append(f"- DOI: `{card.doi}`")
            lines.append("")

        # Readiness assessment
        if card.readiness:
            lines.append("## Analysis Readiness")
            lines.append("")

            score_pct = int(card.readiness.score * 100)
            lines.append(f"**Score: {score_pct}/100**")
            lines.append("")

            if card.readiness.strengths:
                lines.append("### Strengths")
                for s in card.readiness.strengths:
                    lines.append(f"- {s}")
                lines.append("")

            if card.readiness.limitations:
                lines.append("### Limitations")
                for l in card.readiness.limitations:
                    lines.append(f"- {l}")
                lines.append("")

            if card.readiness.missing_metadata:
                lines.append("### Missing Metadata")
                for m in card.readiness.missing_metadata:
                    lines.append(f"- {m}")
                lines.append("")

            if card.readiness.suggested_analyses:
                lines.append("### Suggested Analyses")
                for a in card.readiness.suggested_analyses:
                    lines.append(f"- {a.replace('_', ' ').title()}")
                lines.append("")

        # Extraction details
        if card.extraction and card.extraction.task_labels:
            lines.append("## Extracted Labels")
            lines.append("")

            lines.append("### Tasks")
            for label in card.extraction.task_labels:
                conf_pct = int(label.confidence * 100)
                lines.append(
                    f"- **{label.label}** ({conf_pct}% confidence)"
                )
                lines.append(f"  - Evidence: {label.evidence}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append(
            f"*Generated by Neural Search at {card.generated_at.isoformat()}*"
        )

        return "\n".join(lines)

    def render_compact(self, card: "DatasetCard") -> str:
        """Render a compact card for search results."""
        lines = []

        lines.append(f"### {card.title}")

        # Quick stats
        parts = []
        parts.append(card.source.value.upper())
        if card.species:
            parts.append(card.species[0])
        if card.tasks:
            parts.append(card.tasks[0])
        if card.readiness:
            parts.append(f"{int(card.readiness.score * 100)}% ready")

        lines.append(" | ".join(parts))
        lines.append("")
        lines.append(card.summary)

        return "\n".join(lines)
