"""Build a single, current-state briefing every agent playbook reads first.

Before this module existed, each playbook told the agent to go re-derive
context by grepping files and reading multiple reports from scratch every
run (see `artifacts/agents/playbooks/*.md`). That is correct but slow, and
repeated across every agent, every run. This module collects the same
handful of load-bearing facts once -- production scale, the last known-good
NDCG@10 baseline, each registered agent's last outcome, and the open
questions a prior run already flagged but didn't resolve -- so an agent
starts from a verified baseline instead of rediscovering it.

This is NOT a replacement for the deeper reports it points to (manifest,
coverage reports, ledger). It is a fast, honest entry point: every number
here is read directly from an existing artifact, with that artifact's own
freshness timestamp carried through, so staleness is visible rather than
silently assumed away (the same principle `current_artifact_manifest.json`
itself was built to enforce -- see the `ssot_manifest` project memory).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from neural_search.agents.ledger import last_run_for_agent, load_registry

PROJECT_ROOT = Path(__file__).parent.parent.parent
MANIFEST_PATH = PROJECT_ROOT / "reports" / "eval" / "current_artifact_manifest.json"
AGENTS_DIR = PROJECT_ROOT / "artifacts" / "agents"
OUTPUT_PATH = AGENTS_DIR / "context_brief.md"

# Findings text markers that indicate a prior agent run flagged something as
# genuinely unresolved, rather than just reporting a routine "ok" status.
_OPEN_QUESTION_MARKERS = (
    "UNCLEAR",
    "NEW FINDING",
    "not resolved",
    "needing follow-up",
    "needs follow-up",
    "Proposed action",
)


def _load_manifest() -> dict[str, Any]:
    if not MANIFEST_PATH.exists():
        return {}
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def _extract_open_questions(registry: dict[str, Any]) -> list[dict[str, str]]:
    """Findings from the latest run of each agent that still read as unresolved."""

    open_questions: list[dict[str, str]] = []
    for agent in registry.get("agents", []):
        name = agent["name"]
        last_run = last_run_for_agent(name)
        if not last_run:
            continue
        for finding in last_run.get("findings", []):
            if any(marker in finding for marker in _OPEN_QUESTION_MARKERS):
                open_questions.append({"agent": name, "finding": finding})
    return open_questions


def _agent_status_rows(registry: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for agent in registry.get("agents", []):
        name = agent["name"]
        last_run = last_run_for_agent(name)
        rows.append(
            {
                "name": name,
                "trigger": agent.get("trigger"),
                "schedule_cadence": agent.get("schedule_cadence"),
                "gate": agent.get("gate"),
                "has_playbook": (AGENTS_DIR / agent["playbook"]).exists(),
                "last_run": last_run,
            }
        )
    return rows


def build_context_brief() -> dict[str, Any]:
    """Assemble the structured brief. `render_context_brief_markdown` formats it."""

    manifest = _load_manifest()
    registry = load_registry()

    corpus = manifest.get("corpus", {})
    graph = manifest.get("knowledge_graph", {})
    qrels = manifest.get("qrels", {})
    paper_links = manifest.get("paper_dataset_links", {})
    reanalysis = manifest.get("reanalysis_edges", {})
    ablation = manifest.get("ablation_benchmark", {})
    rungs = ablation.get("rungs", {})

    return {
        "manifest_generated_at": manifest.get("generated_at"),
        "manifest_available": bool(manifest),
        "corpus_rows": corpus.get("row_count"),
        "graph_nodes": graph.get("total_nodes"),
        "graph_edges": graph.get("total_edges"),
        "qrels_gold_rows": qrels.get("gold", {}).get("rows"),
        "qrels_silver_rows": qrels.get("silver", {}).get("rows"),
        "qrels_canonical_rows": qrels.get("canonical_llm_silver", {}).get("rows"),
        "paper_link_combined_real_matches": paper_links.get("combined_datasets_with_real_link"),
        "paper_link_total_rows": paper_links.get("total_rows"),
        "reanalysis_edges": reanalysis,
        "ndcg_baseline": {
            rung: data.get("metrics", {}).get("ndcg@10")
            for rung, data in rungs.items()
            if data.get("status") == "ok"
        },
        "agents": _agent_status_rows(registry),
        "open_questions": _extract_open_questions(registry),
    }


def render_context_brief_markdown(brief: dict[str, Any]) -> str:
    lines = [
        "# Agent Context Brief",
        "",
        "Auto-generated by `neural_search/agents/context_brief.py` from "
        "`reports/eval/current_artifact_manifest.json` and `artifacts/agents/ledger.jsonl`. "
        "Read this first before starting any playbook -- it is not a replacement for the "
        "manifest, coverage reports, or ledger, only a fast, honest entry point into them.",
        "",
        f"Manifest freshness: `{brief['manifest_generated_at']}`"
        if brief["manifest_available"]
        else "**Manifest unavailable** -- run `python scripts/build_artifact_manifest.py` first.",
        "",
        "## Production scale",
        "",
        f"- Corpus rows: {brief['corpus_rows']}",
        f"- Graph: {brief['graph_nodes']} nodes / {brief['graph_edges']} edges",
        f"- Qrels: gold={brief['qrels_gold_rows']}, silver={brief['qrels_silver_rows']}, "
        f"canonical_llm_silver={brief['qrels_canonical_rows']}",
        f"- Paper-dataset links: {brief['paper_link_combined_real_matches']}/"
        f"{brief['paper_link_total_rows']} real matches (combined across 5 sources)",
        "",
        "## Reanalysis/reinterpretation edge counts",
        "",
    ]
    for edge_type, count in brief["reanalysis_edges"].items():
        lines.append(f"- `{edge_type}`: {count}")

    lines.extend(["", "## NDCG@10 baseline (last recorded)", ""])
    for rung, value in brief["ndcg_baseline"].items():
        lines.append(f"- `{rung}`: {value}")

    lines.extend(["", "## Registered agents", "", "| Agent | Trigger | Gate | Playbook exists | Last run | Last outcome |", "|---|---|---|---|---|---|"])
    for row in brief["agents"]:
        last_run = row["last_run"]
        last_run_str = last_run["finished_at"] if last_run else "never run"
        outcome_str = last_run["outcome"] if last_run else "-"
        lines.append(
            f"| {row['name']} | {row['trigger']} | {row['gate']} | "
            f"{'yes' if row['has_playbook'] else '**MISSING**'} | {last_run_str} | {outcome_str} |"
        )

    lines.extend(["", "## Open questions from prior runs (not yet resolved)", ""])
    if brief["open_questions"]:
        for item in brief["open_questions"]:
            lines.append(f"- **{item['agent']}**: {item['finding']}")
    else:
        lines.append("- none flagged")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    brief = build_context_brief()
    markdown = render_context_brief_markdown(brief)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(markdown, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
